{% set name = "loggertools" %}
{% set version = "1.0" %}
{% set sha256 = "ab167a31c8b0f6f0de7eaabf87714193411286f122d9651e4fc90f7825f28f26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loggertools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - loggertools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/loggertools
  summary: 'A Python port of the Control File Functions of Loggertools, the Logger Tools Software of Olaf Kolle, MPI-BGC Jena, (c) 2012.'
  dev_url: https://github.com/mcuntz/loggertools
  license: MIT
  license_file: LICENSE
  description: |
    Python port of the Control File Functions of Loggertools,
    the Logger Tools Software of Olaf Kolle, MPI-BGC Jena, (c) 2012.
    From the Logger Tools Software manual:
    "The functions range from simple mathematic operations to more complex
    and special procedures including functions for checking data. Most of
    the functions have the following appearance: `y = f(x, p1, p2, ..., pn)`
    where `y` is the variable in which the result of the function `f` is
    stored, `x` is the input variable of the function and `p1` to `pn` are
    parameters (numbers) of the function. An output variable (result of a
    function) may be the same as an input variable. Some functions need
    more than one input variable, some functions do not need any parameter
    and some functions (`mean`, `mini`, `maxi`) may have a variable number
    of input variables."
  doc_url: https://mcuntz.github.io/loggertools
  dev_url: https://github.com/mcuntz/loggertools

extra:
  recipe-maintainers:
    - mcuntz
